// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace chd.Poomsae.Scoring.Persistence.CompiledModels
{
    public partial class ScoringContextModel
    {
        private ScoringContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("f539e278-c183-45a0-be52-f99c431355f4"), entityTypeCount: 1)
        {
        }

        partial void Initialize()
        {
            var fighterDto = FighterDtoEntityType.Create(this);

            FighterDtoEntityType.CreateAnnotations(fighterDto);

            AddAnnotation("ProductVersion", "9.0.5");
        }
    }
}
