// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable disable

namespace chd.Poomsae.Scoring.Persistence.CompiledModels
{
    public partial class ScoringContextModel
    {
        private ScoringContextModel()
            : base(skipDetectChanges: false, modelId: new Guid("b324f416-3a23-4f4c-be0b-d9ece20f86bf"), entityTypeCount: 3)
        {
        }

        partial void Initialize()
        {
            var fighterDto = FighterDtoEntityType.Create(this);
            var roundDto = RoundDtoEntityType.Create(this);
            var savedScoreDto = SavedScoreDtoEntityType.Create(this);

            RoundDtoEntityType.CreateForeignKey1(roundDto, fighterDto);
            SavedScoreDtoEntityType.CreateForeignKey1(savedScoreDto, roundDto);

            FighterDtoEntityType.CreateAnnotations(fighterDto);
            RoundDtoEntityType.CreateAnnotations(roundDto);
            SavedScoreDtoEntityType.CreateAnnotations(savedScoreDto);

            AddAnnotation("ProductVersion", "9.0.5");
        }
    }
}
