// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using chd.Poomsae.Scoring.Persistence;
using chd.Poomsae.Scoring.Persistence.CompiledModels;

#pragma warning disable 219, 612, 618
#nullable disable

[assembly: DbContextModel(typeof(ScoringContext), typeof(ScoringContextModel))]
