<Project Sdk="Microsoft.NET.Sdk.Razor">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.22.0" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.22.0" />
	</ItemGroup>
	<ItemGroup>
	  <ProjectReference Include="..\chd.Poomsae.Scoring.Persistence\chd.Poomsae.Scoring.Persistence.csproj" />
	</ItemGroup>
</Project>
