# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET App Branch

on:
  workflow_dispatch:
    inputs: 
      build_config:
        description: 'How to build debug/release'
        required: true
        default: 'Release'
      selected_branch:
        description: 'Branch?'
        required: true
        default: 'main'

jobs:
  build:
    env:
      BUILD_CONFIG: ${{ github.event.inputs.build_config }}
      
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.inputs.selected_branch }}  # <-- Hier deinen Branch-Namen eintragen
   
    - name: Install Maui
      run: dotnet workload install maui 
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Publish
      run: |
        $MAJOR=0
        $MINOR=1
        $YEAR=& Get-Date -UFormat "%y%j"
        $HOUR=& Get-Date -format HHmm
        $VERSION="$MAJOR.$MINOR.$YEAR.$HOUR"
        dotnet publish src/chd.Poomsae.Scoring.App/chd.Poomsae.Scoring.App.csproj --no-restore --configuration ${{ env.BUILD_CONFIG }} --framework net9.0-android /p:ApplicationDisplayVersion=$VERSION /p:ApplicationVersion=${{ github.run_number}} /p:AndroidSigningKeyPass=${{secrets.CHDPOOMSAE_SCORING_KEYPASS}} /p:AndroidSigningStorePass=${{secrets.CHDPOOMSAE_SCORING_KEYPASS}} /p:AndroidKeyStore=true /p:AndroidSigningKeyStore=chdpoomsaescoring.keystore /p:AndroidSigningKeyAlias=chdpoomsaescoring /p:AndroidSigningKeyAlias=chdpoomsaescoring /p:AndroidVersionCode=${{github.run_number}} 
        
    - name: Upload APK Build Artifact
      uses: actions/upload-artifact@v4.4.2
      with:
        name: chdPoomsaeScoring
        path: ./**/bin/Release/**/publish/*.apk
