name: Build MAUI iOS App

on:
  workflow_dispatch: # manuell auslösbar
    inputs: 
      build_config:
        description: 'How to build debug/release'
        required: true
        default: 'Release'
      use_ipa:
        description: 'Create an IPA Artifact'
        required: true
        default: 'true'

jobs:
  build-ios:
    env:
      BUILD_CONFIG: ${{ github.event.inputs.build_config }}
      
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Xcode version
      uses: maxim-lobanov/setup-xcode@v1.6.0
      with:
        xcode-version: 16.0
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.x'

    - name: Install MAUI workloads
      run: |
        dotnet workload install maui
        dotnet workload install maui-ios

    - name: Import Code-Signing Certificates
      uses: Apple-Actions/import-codesign-certs@v1
      with:
        p12-file-base64: ${{ secrets.IOS_P12_B64 }}
        p12-password: ${{ secrets.P12_PASSWORD }}
        
    - name: Download Apple Provisioning Profiles
      uses: Apple-Actions/download-provisioning-profiles@v1
      with:
        bundle-id: 'com.companyname.chd.poomsae.scoring.app'
        issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
        api-key-id: ${{ secrets.APPSTORE_KEY_ID }}
        api-private-key: ${{ secrets.APPSTORE_PRIVATE_KEY }}

    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build MAUI iOS App (Release)
      run: |
        $MAJOR=1
        $MINOR=1
        $YEAR=& Get-Date -UFormat "%y%j"
        $HOUR=& Get-Date -format HHmm
        $VERSION="$MAJOR.$MINOR.$YEAR.$HOUR"
        dotnet publish src/chd.Poomsae.Scoring.App/chd.Poomsae.Scoring.App.csproj --no-restore --configuration ${{ env.BUILD_CONFIG }} --framework net9.0-ios
          /p:ApplicationDisplayVersion=$VERSION 
          /p:ApplicationVersion=${{ github.run_number}} 
          /p:RuntimeIdentifier=ios-arm64 \
          /p:BuildIpa=true \
          /p:CodesignKey="Apple Distribution" \
          /p:CodesignProvision="Your Provisioning Profile Name"

    - name: Upload artifact
      if: ${{ github.event.inputs.use_ipa == 'true' }}
      uses: actions/upload-artifact@v4
      with:
        name: ios-app
        path: ./output/*.ipa
