name: Build MAUI iOS App

on:
  workflow_dispatch: # manuell auslösbar
    inputs: 
      build_config:
        description: 'How to build debug/release'
        required: true
        default: 'Release'
      use_ipa:
        description: 'Create an IPA Artifact'
        required: true
        default: 'true'

jobs:
  build-ios:
    env:
      BUILD_CONFIG: ${{ github.event.inputs.build_config }}
      
    runs-on: macos-15

    steps:
    - uses: actions/checkout@v3

    - name: Select Xcode version
      run: sudo xcode-select -s /Applications/Xcode_16.3.app
    
    #- name: Setup Xcode version
    #  uses: maxim-lobanov/setup-xcode@v1.6.0
    #  with:
     #   xcode-version: latest
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.x'

    - name: Set Datetime
      id: date
      run: |
        echo "year=$(date +%y%j)" >> $GITHUB_OUTPUT
        echo "hour=$(date +%H%M)" >> $GITHUB_OUTPUT
    - name: Define Date Var
      run: echo "DATEVERSION=1.1.${{ steps.date.outputs.year }}.${{ steps.date.outputs.hour }}" >> $GITHUB_ENV
    - name: Write Version
      run: |
        echo ${{env.DATEVERSION}}
        echo "VERSION=${{env.DATEVERSION}}" >> $GITHUB_ENV
        
    - name: Install MAUI workloads
      run: |
        dotnet workload install maui
        dotnet workload install maui-ios

    - name: Import Code-Signing Certificates
      uses: Apple-Actions/import-codesign-certs@v1
      with:
        p12-file-base64: ${{ secrets.IOS_P12_B64 }}
        p12-password: ${{ secrets.P12_PASSWORD }}
        
    - name: Download Apple Provisioning Profiles
      uses: Apple-Actions/download-provisioning-profiles@v1
      with:
        bundle-id: 'com.companyname.chd.poomsae.scoring.app'
        issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
        api-key-id: ${{ secrets.APPSTORE_KEY_ID }}
        api-private-key: ${{ secrets.APPSTORE_PRIVATE_KEY }}

    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build MAUI iOS App (Release)
      run: dotnet publish src/chd.Poomsae.Scoring.App/chd.Poomsae.Scoring.App.csproj --no-restore -f net9.0-ios -c ${{ env.BUILD_CONFIG }} -p:ArchiveOnBuild=true -p:EnableAssemblyILStripping=false

    - name: Upload artifact
      if: ${{ github.event.inputs.use_ipa == 'true' }}
      uses: actions/upload-artifact@v4
      with:
        name: ios-app
        path: ./**/Release/**/publish/*.ipa
